# Generated by Django 4.2 on 2025-01-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNewFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('file_with_tasks', models.FileField(max_length=254, upload_to='files_with_tasks', verbose_name='Файл с заданиями')),
                ('files_for_test', models.FileField(max_length=254, upload_to='files_for_tasks', verbose_name='Файл для заданий')),
                ('number_of_inputs', models.IntegerField(verbose_name='Кол-во полей ввода в тесте')),
                ('file_with_answers', models.FileField(max_length=254, upload_to='files_with_answers', verbose_name='Файл с ответами')),
                ('number_of_attempts', models.IntegerField(blank=True, default=1, verbose_name='Количество попыток')),
                ('count_right_answers', models.IntegerField(blank=True, null=True, verbose_name='Количество верных ответов')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершён ли тест')),
                ('generate_random_order_tasks', models.BooleanField(default=False, verbose_name='Генерировать вопросы в перемешку')),
                ('is_show_answers', models.BooleanField(default=False, verbose_name='Показывать ответы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тест нового образца',
                'verbose_name_plural': 'Тесты нового образца',
            },
        ),
    ]
