# Generated by Django 4.2 on 2025-02-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnewformat',
            name='files_for_test',
        ),
        migrations.CreateModel(
            name='FilesForTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_for_test', models.FileField(max_length=254, upload_to='files_for_tasks', verbose_name='Файл для заданий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test_new_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='teacher_app.testnewformat')),
            ],
        ),
    ]
