# Generated by Django 4.2 on 2025-02-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_remove_testnewformat_files_for_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesfortestmodel',
            old_name='files_for_test',
            new_name='file',
        ),
    ]
