# Generated by Django 4.2 on 2025-02-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_rename_files_for_test_filesfortestmodel_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesfortestmodel',
            options={'verbose_name': 'Файл для теста нового образца', 'verbose_name_plural': 'Файлы для теста нового образца'},
        ),
        migrations.RemoveField(
            model_name='testnewformat',
            name='generate_random_order_tasks',
        ),
    ]
