# Generated by Django 4.2 on 2025-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_alter_filesfortestmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnewformat',
            name='input_with_number_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
