# Generated by Django 4.2 on 2025-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0005_testnewformat_input_with_number_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnewformat',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название теста'),
        ),
    ]
