# Generated by Django 4.2 on 2025-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='has_correct_answer',
            new_name='has_answers',
        ),
        migrations.RenameField(
            model_name='questiontype',
            old_name='template_name',
            new_name='template',
        ),
        migrations.AddField(
            model_name='questiontype',
            name='verbose_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
