# Generated by Django 4.2 on 2025-04-18 20:36

from django.db import migrations

def add_initial_question_types(apps, schema_editor):
    QuestionType = apps.get_model('quiz', 'QuestionType')
    types = [
        {'name': 'single', 'verbose_name': 'Один вариант', 'template': 'single.html', 'has_answers': True},
        {'name': 'multiple', 'verbose_name': 'Несколько вариантов', 'template': 'multiple.html', 'has_answers': True},
        {'name': 'text', 'verbose_name': 'Текстовый ответ', 'template': 'text.html', 'has_answers': False}
    ]
    for type_data in types:
        QuestionType.objects.create(**type_data)


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_has_correct_answer_questiontype_has_answers_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_question_types)
    ]
