# Generated by Django 4.2 on 2025-04-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20250418_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='universaltest',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='universaltest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test'),
        ),
        migrations.DeleteModel(
            name='UniversalTest',
        ),
    ]
