# Generated by Django 4.2 on 2025-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_test_remove_testattempt_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('EX', 'Экзамен'), ('QZ', 'Быстрый тест'), ('PR', 'Тренировка'), ('SR', 'Опрос'), ('PS', 'Психологический тест')], default='QZ', max_length=2, verbose_name='Тип теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если без ограничений', null=True, verbose_name='Лимит времени (в мин)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
