# Generated by Django 4.2 on 2025-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_test_created_at_test_description_test_test_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SN', 'Одиночный'), ('ML', 'Мульти'), ('TX', 'Текстовый')], default='SN', max_length=2, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Только если вопрос текстовый'),
        ),
    ]
