# Generated by Django 4.2 on 2025-04-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_alter_question_question_type_alter_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('members', models.ManyToManyField(blank=True, related_name='learning_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='Доступен с')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='Доступен до')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.group')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test')),
            ],
            options={
                'verbose_name': 'Доступ теста к группе',
                'verbose_name_plural': 'Настройки доступа тестов',
                'unique_together': {('test', 'group')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tests', through='quiz.TestGroupAccess', to='quiz.group', verbose_name='Доступные группы'),
        ),
    ]
