# Generated by Django 4.2 on 2025-04-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_group_testgroupaccess_test_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
