# Generated by Django 4.2 on 2025-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_fuzzy_match',
            field=models.BooleanField(default=False, help_text='Если включено, система будет учитывать опечатки и синонимы', verbose_name='Нечеткое сравнение ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ (для автопроверки)'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальный балл'),
        ),
    ]
