# Generated by Django 4.2 on 2025-04-25 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_testgroupaccess_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 25, 6, 7, 11, 224309, tzinfo=datetime.timezone.utc), null=True, verbose_name='Доступен с'),
        ),
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 6, 7, 11, 224328, tzinfo=datetime.timezone.utc), null=True, verbose_name='Доступен до'),
        ),
    ]
