# Generated by Django 4.2 on 2025-04-25 18:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 25, 18, 30, 45, 355238, tzinfo=datetime.timezone.utc), null=True, verbose_name='Доступен с'),
        ),
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 18, 30, 45, 355252, tzinfo=datetime.timezone.utc), null=True, verbose_name='Доступен до'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Правильный ответ')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Начисленные баллы')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('check_status', models.CharField(choices=[('review', 'Требуется проверка'), ('auto', 'Автоматическая проверка'), ('manual', 'Проверено вручную')], default='auto', max_length=10, verbose_name='Статус проверки')),
                ('admin_review_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.question')),
                ('selected_answers', models.ManyToManyField(blank=True, to='quiz.answer')),
                ('user_test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.usertestresult')),
            ],
            options={
                'unique_together': {('user_test_result', 'question')},
            },
        ),
    ]
