# Generated by Django 4.2 on 2025-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_testgroupaccess_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_from',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Доступен с'),
        ),
        migrations.AlterField(
            model_name='testgroupaccess',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен до'),
        ),
    ]
