# Generated by Django 4.2 on 2025-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_testgroupaccess_available_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'verbose_name': 'Результат пользователя по тесту', 'verbose_name_plural': 'Результат пользователя по тестам'},
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пояснение к заданию'),
        ),
    ]
