# Generated by Django 4.2 on 2025-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_test_results_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Результат пользователя по тесту', 'verbose_name_plural': 'Результат пользователя по тестам'},
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='max_score',
            field=models.FloatField(default=1, verbose_name='Максимальный балл'),
        ),
    ]
