# Generated by Django 4.2 on 2025-05-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_test_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начат в'),
        ),
    ]
