# Generated by Django 4.2 on 2025-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_usertestresult_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начат в'),
        ),
    ]
