# Generated by Django 4.2 on 2025-05-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_usertestresult_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
