# Generated by Django 4.2 on 2024-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_attempts',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
