# Generated by Django 5.0.7 on 2024-07-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link_to_answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
