# Generated by Django 5.0.7 on 2024-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='count_right_answers',
            field=models.IntegerField(blank=True),
        ),
    ]
