# Generated by Django 5.0.7 on 2024-07-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_test_count_right_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='task_numbers',
        ),
        migrations.AddField(
            model_name='test',
            name='task_numbers',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
