# Generated by Django 5.0.7 on 2024-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_test_count_right_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link_to_answer',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
