# Generated by Django 5.0.7 on 2024-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='right_answers',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
