# Generated by Django 4.2 on 2024-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_test_number_of_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(default='Задание ', max_length=255),
        ),
    ]
