# Generated by Django 4.2 on 2024-09-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_task_title_alter_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='current_attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
