# Generated by Django 4.2 on 2024-09-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_test_current_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='current_attempts',
        ),
        migrations.AddField(
            model_name='usertest',
            name='current_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='number_of_attempts',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
