# Generated by Django 4.2 on 2024-09-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='Изображение пользователя', max_length=200),
        ),
    ]
