# Generated by Django 4.2 on 2024-09-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
