# Generated by Django 4.2 on 2024-09-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_customuser_open_password_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
