# Generated by Django 4.2 on 2024-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_remove_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_main_name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='open_password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
