# Generated by Django 4.2 on 2024-09-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_customuser_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
    ]
