# Generated by Django 4.2 on 2024-10-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_subjectmain_remove_customuser_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_parent_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=1)),
                ('timestamps', models.CharField(blank=True, max_length=255)),
                ('subject_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.subjectmain')),
            ],
        ),
    ]
