# Generated by Django 4.2 on 2024-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_customuser_login_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_child',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject_parent',
        ),
    ]
