# Generated by Django 4.2 on 2024-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_remove_customuser_login_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject_child',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject_parent',
            field=models.IntegerField(),
        ),
    ]
