# Generated by Django 4.2 on 2024-10-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_remove_customuser_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='subject_child_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject_child',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject_parent',
            new_name='subject_parent_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
    ]
