# Generated by Django 4.2 on 2024-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_rename_subject_question_subject_child_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enabled',
            field=models.BooleanField(default=1),
        ),
    ]
