# Generated by Django 4.2 on 2024-11-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_question_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='generate_random_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
