# Generated by Django 4.2 on 2024-11-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0023_remove_test_generate_random_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_show_answers',
            field=models.BooleanField(default=False, verbose_name='Показывать ответы?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='count_right_answers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество верных ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершён ли тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='number_of_attempts',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='test',
            name='task_numbers',
            field=models.CharField(max_length=255, verbose_name='ID заданий'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название теста'),
        ),
    ]
