# Generated by Django 4.2 on 2024-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_test_is_show_answers_alter_test_count_right_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_show_answers',
            field=models.BooleanField(default=False),
        ),
    ]
