# Generated by Django 4.2 on 2024-11-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_usertest_is_show_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='is_show_answers',
        ),
        migrations.AlterField(
            model_name='test',
            name='is_show_answers',
            field=models.BooleanField(default=False, verbose_name='Показывать ответы'),
        ),
    ]
