# Generated by Django 4.2 on 2024-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_alter_answer_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
