# Generated by Django 4.2 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='file_with_answers',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='files_with_answers', verbose_name='Файл с ответами'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='file_with_tasks',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='files_with_tasks', verbose_name='Файл с заданиями'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='number_of_inputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во полей ввода в тесте'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='tasks_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
