# Generated by Django 4.2 on 2025-02-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_usertest_file_with_answers_usertest_file_with_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='file_with_answers',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='file_with_tasks',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='number_of_inputs',
        ),
    ]
