# Generated by Django 4.2 on 2025-03-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0032_remove_usertest_file_with_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
